# Run django server
server:
	poetry run python3 django_core/manage.py runserver
# Database migrations
migrations:
	poetry run python3 django_core/manage.py makemigrations
migrate:
	poetry run python3 django_core/manage.py migrate
