# Generated by Django 5.0.6 on 2024-06-17 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(choices=[("DM", "DM")], default="DM", max_length=10),
        ),
    ]
