# Generated by Django 5.0.6 on 2024-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="member",
            new_name="members",
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="7067798558", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
