# Generated by Django 5.0.1 on 2024-01-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_user_chatroom_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmsg",
            old_name="message",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_message",
                to="chat.chatroom",
            ),
        ),
    ]
