# Generated by Django 5.0.6 on 2024-06-20 08:22

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_rename_member_chatroom_members_alter_chatroom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="avatar/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="4202177511", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
