# Generated by Django 5.0.6 on 2024-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatroom_avatar_chatroom_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="9801226411", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
