# Generated by Django 5.0.6 on 2024-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatroom_bio_alter_chatroom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="color",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="1771766007", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
