# Generated by Django 5.0.6 on 2024-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatroom_color_alter_chatroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="1150711532", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
