# Generated by Django 5.0.2 on 2024-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_rename_user_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
