# Generated by Django 5.0.6 on 2024-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_chatroom_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default="6398341390", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
