# Generated by Django 5.0.2 on 2024-02-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chatmessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[(1, "text"), (2, "image"), (3, "video")],
                default=1,
                max_length=10,
            ),
        ),
    ]
