# Generated by Django 5.0.2 on 2024-02-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_chatmessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[("TXT", "text"), ("IMG", "image"), ("VID", "video")],
                default="TXT",
                max_length=10,
            ),
        ),
    ]
