# Generated by Django 5.0.2 on 2024-02-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_chatmessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[("text", "text"), ("image", "image"), ("gif", "gif")],
                default="text",
                max_length=10,
            ),
        ),
    ]
