# Generated by Django 5.0.2 on 2024-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_chatmessage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
