# Generated by Django 4.2.6 on 2023-10-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
