# Generated by Django 5.0.6 on 2024-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="color",
            field=models.CharField(blank=True, null=True),
        ),
    ]
