# Generated by Django 4.2.6 on 2023-10-15 09:17

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_customuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="avatar/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
