# Generated by Django 5.0 on 2024-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
