# Generated by Django 5.0.1 on 2024-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="online",
            field=models.IntegerField(default=0),
        ),
    ]
