# Generated by Django 5.0.1 on 2024-01-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_remove_customuser_online_onlineuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
